language: node_js
node_js:
  - "10"

after_success:
  - git config --global user.name "xgamecoindev"
  - git config --global user.email "xgamecoindev@users.noreply.github.com"
  - git remote rm origin
  - git remote add origin https://xgamecoindev:${GH_TOKEN}@github.com/xgamecoindev/xgamebits.org.git
  - npm run deploy
